# Generated by Django 4.1.6 on 2023-02-13 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrupaRobocza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=15)),
                ('aktywna', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('aktywna', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Narzedzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupa', models.CharField(max_length=15)),
                ('uwagi', models.CharField(blank=True, max_length=150, null=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Przekroje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('przekroj', models.CharField(max_length=7)),
                ('wartosc', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rozciagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zlecenia', models.CharField(max_length=10)),
                ('nr_pozycji', models.CharField(max_length=250)),
                ('nr_pracownika', models.DecimalField(decimal_places=0, max_digits=5)),
                ('rozciag', models.DecimalField(decimal_places=0, max_digits=5)),
                ('indeks_kontaktu', models.CharField(max_length=10)),
                ('poprawkowe', models.BooleanField(default=False)),
                ('narzedzia', models.CharField(max_length=20)),
                ('wysokosc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('data_serwis', models.DateField(blank=True, null=True, verbose_name='data serwis')),
                ('data_dodania', models.DateField(verbose_name='data dodania')),
                ('potwierdzenie', models.BooleanField(default=False)),
                ('grupa_robocza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciagi.gruparobocza')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciagi.listy')),
                ('narzedzia_rodzaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciagi.narzedzia')),
                ('przekrojePrzewodow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciagi.przekroje')),
                ('zalogowany_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rozciagi.author')),
            ],
        ),
    ]
